name: 'Docker Image CI'
on:
  push:
    branches:
      - main


jobs:
  build:
    name: 'Docker'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Setup Docker 
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12

    - name: Building docker image
      run: docker build . -t my-app:practicesreeramrepo:latest 
      working-directory: "./"

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker Push
      run: |
        docker push ${{secrets.DOCKER_USER}}/practicesreeramrepo







