name: 'Docker Image CI'
on:
  workflow_dispatch: {}
  push:
    branches:
      - main


jobs:
  build:
    name: 'Docker'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Setup Docker 
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Building docker image
      run: docker build . -t my-app:1.0
      working-directory: "./"

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER1}}
        TOKEN: ${{secrets.ECR_TOKEN}}
      run: |
        docker login -u AWS -p $TOKEN 675920801761.dkr.ecr.us-east-2.amazonaws.com

    - name: Docker Push
      run: |
        docker tag my-app:1.0 675920801761.dkr.ecr.us-east-2.amazonaws.com/practice-repo
        docker push 675920801761.dkr.ecr.us-east-2.amazonaws.com/practice-repo

    - name: Git clone helm repo
      run : |
        git clone https://github.com/hotshotsreeram/helm-sample.git

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.KEY }}
        known_hosts: unnecessary

    - name: ssh into matchine
      uses: appleboy/ssh-action@v0.1.7
      env:
        env:
        DOCKER_USER: ${{secrets.DOCKER_USER1}}
        TOKEN: ${{secrets.ECR_TOKEN}}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          ls -al
          docker login -u AWS --password-stdin ${{secrets.ECR_TOKEN}} 675920801761.dkr.ecr.us-east-2.amazonaws.com/practice-repo
          docker pull 675920801761.dkr.ecr.us-east-2.amazonaws.com/practice-repo:latest
          docker stop my-practice
          docker rm my-practice
          docker run -d --restart unless-stopped --name my-practice -p 8080:80 675920801761.dkr.ecr.us-east-2.amazonaws.com/practice-repo 
          docker ps
          whoami

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Deploying load balancer
      id: init
      run: |
        cd elb
        terraform init
        terraform plan -var-file="values.tfvars"
        terraform apply -var-file="values.tfvars" -auto-approve

    - name: Creating AMI
      id: ami
      run: |
        cd ami
        terraform init
        terraform destroy -var-file="values.tfvars" -auto-approve
        terraform plan -var-file="values.tfvars"
        terraform apply -var-file="values.tfvars" -auto-approve






