name: 'Docker Image CI'
on:
  workflow_dispatch: {}
  push:
    branches:
      - main


jobs:
  build:
    name: 'Docker'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Setup Docker 
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12

    - name: Building docker image
      run: docker build . -t my-app:1.0
      working-directory: "./"

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker Push
      run: |
        docker tag my-app:1.0 ${{secrets.DOCKER_USER}}/practicesreeramrepo
        docker push ${{secrets.DOCKER_USER}}/practicesreeramrepo

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Git clone helm repo
      run : |
        git clone https://github.com/hotshotsreeram/helm-sample.git

    - name: ssh into matchine
      env:
        MY_PRACTICE: ${{secrets.MY_PRACTICE}}
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "$MY_PRACTICE" > My_practice.pem && chmod 600 My_practice.pem
        ssh -o StrictHostKeyChecking=no -i My_practice.pem ubuntu@44.201.28.29
        ls -al
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker pull sreeramdockerrepo/practicesreeramrepo:latest
        docker run -d -p 8080:80 sreeramdockerrepo/practicesreeramrepo
        docker ps
        pwd

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Deploying load balancer
      id: init
      run: |
        cd elb
        terraform init
        terraform plan -var-file="values.tfvars"
        terraform apply -var-file="values.tfvars" -auto-approve






